### PR TITLE
Include DPCT headers from system installation and remove the local copy

### PR DESCRIPTION
**Pull request by rafbiels**
* Remove the outdated copy of DPCT headers in `src_sycl/include`
* Add cmake find module for DPCT
* Use the DPCT headers in `src_sycl/CMakeLists.txt` from the cmake module

The DPCT is part of the oneAPI base toolkit so if `dpcpp`/`icpx` is available, it is almost certain `dpct` is also installed. The find module looks in the most common oneAPI installation paths and standard system header locations. It works out of the box in the oneAPI environment (after sourcing the `setvars.sh` script). It is also possible to specify the location during cmake configuration using `-Ddpct_LOCATION=/my/custom/location`.

### CODE REVIEW

**Comment by rodburns** [comment]
@joeatodd Can you please confirm you are happy with the approach?

**Comment by irudkin** [comment]
Why did the project use its own local copy of some of the SDK files?

**Comment by irudkin** [comment]
Taking the zip of this version of the project and coping it over to Slurm to build in parallel with the 'main' version, I got the following error when building the nbody_dpcpp.sh:  (using module cuda/11.7.1)

[ 93%] Building CXX object src_sycl/CMakeFiles/nbody_dpcpp.dir/shader.cpp.o
clang++: warning: CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version]
[100%] Linking CXX executable /home/illya/Dev/CodeplayExamples/cuda-to-sycl-nbody-dpct-includes/nbody_dpcpp
clang++: warning: linked binaries do not contain expected 'nvptx64-nvidia-cuda' target; found targets: 'spir64-unknown-unknown, nvptx64-nvidia-cuda-sm_86' [-Wsycl-target]
clang++: warning: CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version]
error: linking module flags 'nvvm-reflect-ftz': IDs have conflicting override values in '/tmp/clang++-e3eee6/libsycl-crt-0c2141.cubin' and 'llvm-link'
clang++: error: sycl-link command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src_sycl/CMakeFiles/nbody_dpcpp.dir/build.make:200: /home/illya/Dev/CodeplayExamples/cuda-to-sycl-nbody-dpct-includes/nbody_dpcpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:116: src_sycl/CMakeFiles/nbody_dpcpp.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by rafbiels** [comment]
Hi @irudkin, the linker error has a workaround described here:  
https://developer.codeplay.com/products/oneapi/nvidia/2023.0.0/guides/troubleshooting#linking-error-with-nvvm-reflect-ftz

**Comment by irudkin** [comment]
Can I suggest, it would be good to have this linking issue with nvvm-reflect-ftz mentioned in the readme.md build section (mentioning the version of oneAPI/DPCPP) for others who may run into this problem.

**Comment by irudkin** [comment]
The cmake scripts use dpcpp the compiler. Should the project be changed to use the Intel icpx compiler and so remove any "dpcpp is being depreciated" warnings?

**Comment by rafbiels** [comment]
Hi @irudkin, these are good suggestions. Let's follow up in https://github.com/codeplaysoftware/cuda-to-sycl-nbody/issues/25 as these issues are not related to the DPCT headers which are addressed in this PR.

**Review by DuncanMcBain — APPROVED** [review]

**Pull request merged**
