### PR TITLE
Cleanup the code, add new option to limit the no. of frames and switch to SYCL 2020 

### PR DESCRIPTION
**Pull request by nmnobre**
Hi @joeatodd,

I've now had the chance to go through all the changes I did to your code in Durham and decided they'd be of better use if shared with the community for future workshops or hackathons. Please see this as a small "thank you" gesture. :)

I spent some time today tidying the code a bit and tested it with the latest versions of both the open-source and the production flavours of the intel compiler. I've also rebased the `no-gfx` branch on my fork and I can create a PR for that as well once this is merged if that'd be helpful.

Cheers,
-Nuno

### CODE REVIEW

**Comment by rodburns** [comment]
Thanks for the PR and apologies for the delay. We'll take a proper review of this in due course.

**Review by DuncanMcBain — APPROVED** [review]

**Comment by DuncanMcBain** [comment]
Thanks @nmnobre , it's showing a minor conflict in the CMake - I'm happy to resolve it if you don't have the time at the moment. Otherwise this looks really good!

**Comment by nmnobre** [comment]
> Thanks @nmnobre , it's showing a minor conflict in the CMake - I'm happy to resolve it if you don't have the time at the moment. Otherwise this looks really good!

Hi @DuncanMcBain, thanks for taking the time to review this. :)
I've resolved the small conflict, so it should be squeaky clean now.

Cheers,
-Nuno

**Comment by DuncanMcBain** [comment]
Brilliant, thank you very much!

**Pull request merged**
